spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ttsweb
    password: China8620
    url: jdbc:mysql://10.0.0.138/MyTest?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
girl:
  age: 22
  name: lily
boy:
  age: 22
