spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ttsweb
    password: China8620
    url: jdbc:mysql://10.0.0.138/MyTest?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
env:
  dev1
girl:
  age: 33333
  name: rommy+++-goodma
